CREATE DATABASE DIEMTHI
USE DIEMTHI

SELECT TOP 1000 * FROM DiemThiHN2017

/*
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'DiemThiHN2017';
*/

--Lay ra SBD va diem thi cac mon khoi A, A1 tuong ung va chuyen kieu du lieu diem sang float
SELECT SOBAODANH, 
CASE
	WHEN DIEM_THI like 'T[oan]%' THEN CAST(SUBSTRING(DIEM_THI, (CHARINDEX(N'Toán', DIEM_THI) + 7), 5) AS FLOAT)
	END AS DIEMTOAN,
CASE	
	WHEN DIEM_THI like '%V___l%' THEN CAST(SUBSTRING(DIEM_THI, (CHARINDEX(N'Vật lí', DIEM_THI) + 9), 5) AS FLOAT)
	END AS DIEMLY, 
CASE	
	WHEN DIEM_THI like '%H__ __c:%' THEN CAST(SUBSTRING(DIEM_THI, (CHARINDEX(N'Hóa học:', DIEM_THI) + 10), 5) AS FLOAT)
	END AS DIEMHOA,
CASE	
	WHEN DIEM_THI like '%T___g Anh:%' THEN CAST(SUBSTRING(DIEM_THI, (CHARINDEX(N'Tiếng Anh:', DIEM_THI) + 12), 5) AS FLOAT)
	END AS DIEMANH
into KHOIAA1 FROM DiemThiHN2017

SELECT * FROM KHOIAA1
Order by (DIEMTOAN + DIEMLY + DIEMHOA + DIEMANH) DESC

--Q1 Top 3 thi sinh co diem khoi A, A1 cao nhat 2017
	--KHOI A
	SELECT TOP 3 DiemThiHN2017.HO_TEN, KHOIAA1.SOBAODANH, 
	             DIEMTOAN, DIEMLY, DIEMHOA 
	FROM DiemThiHN2017 INNER JOIN KHOIAA1
		 ON DiemThiHN2017.SOBAODANH = KHOIAA1.SOBAODANH
	ORDER BY (DIEMTOAN + DIEMLY + DIEMHOA) DESC

	--KHOI A1
	SELECT TOP 3 DiemThiHN2017.HO_TEN, KHOIAA1.SOBAODANH, 
			   DIEMTOAN, DIEMLY, DIEMANH
	FROM DiemThiHN2017 INNER JOIN KHOIAA1
		 ON DiemThiHN2017.SOBAODANH = KHOIAA1.SOBAODANH
	ORDER BY (DIEMTOAN + DIEMLY + DIEMANH) DESC


--Q2 Tinh diem trung binh khoi A, A1 2017
--KHOI A
SELECT ROUND(AVG(DIEMTOAN + DIEMLY + DIEMHOA), 2) as Diem_TB_KhoiA FROM KHOIAA1
WHERE DIEMTOAN IS NOT NULL AND 
	  DIEMLY IS NOT NULL AND 
	  DIEMHOA IS NOT NULL

--KHOI A1
SELECT ROUND(AVG(DIEMTOAN + DIEMLY + DIEMANH), 2) as Diem_TB_KhoiA1 FROM KHOIAA1
WHERE DIEMTOAN IS NOT NULL AND 
	  DIEMLY IS NOT NULL AND 
	  DIEMANH IS NOT NULL


--Q3 So diem ma nhieu thi sinh dat duoc nhat khoi A, A1 
-- (Chi tinh nhung thi sinh tham gia thi day du ca 3 mon cua to hop)
--KHOI A
WITH MucDiemKhoiA_CTE AS
(
	SELECT ROUND((DIEMTOAN + DIEMLY + DIEMHOA), 2) AS CacMucDiemKhoiA 
	FROM KHOIAA1 
	WHERE DIEMTOAN IS NOT NULL AND 
		  DIEMLY IS NOT NULL AND 
		  DIEMHOA IS NOT NULL
)
SELECT TOP 5 CacMucDiemKhoiA, COUNT(*) AS SoLuongThiSinhDatMucDiemTuongUng 
FROM MucDiemKhoiA_CTE
GROUP BY CacMucDiemKhoiA
ORDER BY SoLuongThiSinhDatMucDiemTuongUng DESC
--> 19.95 & 20.1 la hai so diem ma nhieu thi sinh khoi A dat duoc nhat

-- NO CTE
/*
SELECT TOP 5 
    ROUND(DIEMTOAN + DIEMLY + DIEMHOA, 2) AS CacMucDiemKhoiA,
    COUNT(*) AS SoLuongThiSinhDatMucDiemTuongUng
FROM KHOIAA1
WHERE DIEMTOAN IS NOT NULL
	  AND DIEMLY IS NOT NULL
	  AND DIEMHOA IS NOT NULL
GROUP BY ROUND(DIEMTOAN + DIEMLY + DIEMHOA, 2)
ORDER BY SoLuongThiSinhDatMucDiemTuongUng DESC;
*/

--KHOI A1
WITH MucDiemKhoiA1_CTE AS
(
	SELECT ROUND((DIEMTOAN + DIEMLY + DIEMANH), 2) AS CacMucDiemKhoiA1 FROM KHOIAA1 
	WHERE DIEMTOAN IS NOT NULL AND 
		  DIEMLY IS NOT NULL AND 
		  DIEMANH IS NOT NULL
)
SELECT TOP 5 CacMucDiemKhoiA1, COUNT(*) AS SoLuongThiSinhDatMucDiemTuongUng 
FROM MucDiemKhoiA1_CTE
GROUP BY CacMucDiemKhoiA1
ORDER BY SoLuongThiSinhDatMucDiemTuongUng DESC
--> 18.6 & 20.15 la hai so diem ma nhieu thi sinh khoi A1 dat duoc nhat

--Q3.1 Thong ke so luong thi sinh theo cac muc diem khoi A, A1 nam 2017
-- (Chi tinh nhung thi sinh tham gia thi day du ca 3 mon cua top hop)
--KHOI A
SELECT ROUND((DIEMTOAN + DIEMLY + DIEMHOA), 2) AS CacMucDiemKhoiA,
	   COUNT(*) AS SoLuongThiSinhDatMucDiemTuongUng 
FROM KHOIAA1 
WHERE DIEMTOAN IS NOT NULL AND 
	  DIEMLY IS NOT NULL AND 
	  DIEMHOA IS NOT NULL
GROUP BY ROUND((DIEMTOAN + DIEMLY + DIEMHOA), 2)
ORDER BY CacMucDiemKhoiA DESC

--KHOI A1
SELECT ROUND((DIEMTOAN + DIEMLY + DIEMANH), 2) AS CacMucDiemKhoiA1,
	   COUNT(*) AS SoLuongThiSinhDatMucDiemTuongUng 
FROM KHOIAA1 
WHERE DIEMTOAN IS NOT NULL AND 
	  DIEMLY IS NOT NULL AND 
	  DIEMANH IS NOT NULL
GROUP BY ROUND((DIEMTOAN + DIEMLY + DIEMANH), 2)
ORDER BY CacMucDiemKhoiA1 DESC


--Q4 Thong ke so diem liet theo cac mon khoi A, A1 va ty le diem liet tuong ung
SELECT
    SUM(CASE WHEN DIEMTOAN <= 1 THEN 1 ELSE 0 END) AS SoDiemLiet_Toan,
	COUNT(DIEMTOAN) AS ThiSinhThiMonToan,
    CAST(100.0 * SUM(CASE WHEN DIEMTOAN <= 1 THEN 1 ELSE 0 END) / COUNT(DIEMTOAN) AS DECIMAL(5,2)) AS TyLeLiet_Toan,
    
    SUM(CASE WHEN DIEMLY <= 1 THEN 1 ELSE 0 END) AS SoDiemLiet_Ly,
	COUNT(DIEMLY) AS ThiSinhThiMonLy,
    CAST(100.0 * SUM(CASE WHEN DIEMLY <= 1 THEN 1 ELSE 0 END) / COUNT(DIEMLY) AS DECIMAL(5,2)) AS TyLeLiet_Ly,
    
    SUM(CASE WHEN DIEMHOA <= 1 THEN 1 ELSE 0 END) AS SoDiemLiet_Hoa,
	COUNT(DIEMHOA) AS ThiSinhThiMonHoa,
    CAST(100.0 * SUM(CASE WHEN DIEMHOA <= 1 THEN 1 ELSE 0 END) / COUNT(DIEMHOA) AS DECIMAL(5,2)) AS TyLeLiet_Hoa,
    
    SUM(CASE WHEN DIEMANH <= 1 THEN 1 ELSE 0 END) AS SoDiemLiet_Anh,
	COUNT(DIEMANH) AS ThiSinhThiMonAnh,
    CAST(100.0 * SUM(CASE WHEN DIEMANH <= 1 THEN 1 ELSE 0 END) / COUNT(DIEMANH) AS DECIMAL(5,2)) AS TyLeLiet_Anh
FROM KHOIAA1


--Q4.1 Tat ca nhung thi sinh co diem liet thuoc cac mon khoi A, A1
SELECT DiemThiHN2017.HO_TEN, KHOIAA1.SOBAODANH,
	   DIEMTOAN, DIEMLY, DIEMHOA, DIEMANH
FROM DiemThiHN2017 INNER JOIN KHOIAA1 
     ON DiemThiHN2017.SOBAODANH = KHOIAA1.SOBAODANH
WHERE DIEMTOAN <= 1 OR 
	  DIEMLY <= 1 OR 
	  DIEMHOA <= 1 OR 
	  DIEMANH <= 1
ORDER BY SOBAODANH;


--Q5 Nhung thi sinh thi khoi A, A1 co diem liet 2017
-- (Chi tinh nhung thi sinh tham gia thi day du ca 3 mon cua top hop)
-- KHOI A
SELECT DiemThiHN2017.HO_TEN, KHOIAA1.SOBAODANH, 
	   DIEMTOAN, DIEMLY, DIEMHOA
FROM DiemThiHN2017 INNER JOIN KHOIAA1 
     ON DiemThiHN2017.SOBAODANH = KHOIAA1.SOBAODANH
WHERE (DIEMTOAN IS NOT NULL AND DIEMLY IS NOT NULL AND DIEMHOA IS NOT NULL) AND 
	  (DIEMTOAN <=1 OR DIEMLY <=1 OR DIEMHOA <=1)


--KHOI A1
SELECT DiemThiHN2017.HO_TEN, KHOIAA1.SOBAODANH,
	   DIEMTOAN ,DIEMLY, DIEMANH
FROM DiemThiHN2017 INNER JOIN KHOIAA1 
     ON DiemThiHN2017.SOBAODANH = KHOIAA1.SOBAODANH
WHERE (DIEMTOAN IS NOT NULL AND DIEMLY IS NOT NULL AND DIEMANH IS NOT NULL) 
      AND (DIEMTOAN <=1 OR DIEMLY <=1 OR DIEMANH <=1)


--Q6 Cho biet nhung thi sinh co diem thi tu 27 diem tro len cua khoi A, A1 2017
--KHOI A
SELECT DiemThiHN2017.HO_TEN, KHOIAA1.SOBAODANH, 
	   DIEMTOAN, DIEMLY, DIEMHOA 
FROM DiemThiHN2017 INNER JOIN KHOIAA1 
     ON DiemThiHN2017.SOBAODANH = KHOIAA1.SOBAODANH
WHERE (DIEMTOAN + DIEMLY + DIEMHOA) >= 27 
ORDER BY DIEMTOAN DESC, DIEMLY DESC, DIEMHOA DESC

--KHOI A1
SELECT DiemThiHN2017.HO_TEN, KHOIAA1.SOBAODANH, 
	   DIEMTOAN, DIEMLY, DIEMANH 
FROM DiemThiHN2017 INNER JOIN KHOIAA1 
     ON DiemThiHN2017.SOBAODANH = KHOIAA1.SOBAODANH
WHERE (DIEMTOAN + DIEMLY + DIEMANH) >= 27 
ORDER BY DIEMTOAN DESC, DIEMLY DESC, DIEMANH DESC



--Q7 Cho biet nhung thi sinh co diem thi tu 24 diem tro len cua khoi A nhung liet mon anh 2017
SELECT DiemThiHN2017.HO_TEN, KHOIAA1.SOBAODANH, 
	   DIEMTOAN, DIEMLY, DIEMHOA, DIEMANH 
FROM DiemThiHN2017 INNER JOIN KHOIAA1 
     ON DiemThiHN2017.SOBAODANH = KHOIAA1.SOBAODANH
WHERE (DIEMTOAN + DIEMLY + DIEMHOA) >= 24 AND DIEMANH <=1
ORDER BY DIEMTOAN DESC, DIEMLY DESC, DIEMHOA DESC


--Q8 Cho biet nhung thi sinh co diem thi tu 24 diem tro len cua khoi A1 nhung liet mon hoa 2017
SELECT DiemThiHN2017.HO_TEN, KHOIAA1.SOBAODANH, 
	   DIEMTOAN, DIEMLY, DIEMANH, DIEMHOA 
FROM DiemThiHN2017 INNER JOIN KHOIAA1 
     ON DiemThiHN2017.SOBAODANH = KHOIAA1.SOBAODANH
WHERE (DIEMTOAN + DIEMLY + DIEMANH) >= 24 AND DIEMHOA <=1
ORDER BY DIEMTOAN DESC, DIEMLY DESC, DIEMHOA DESC
